codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "0..100"
  status:
    project:
      default:
        # Ratchet: allow up to 1% drop vs base
        target: auto
        threshold: 1%
        base: auto
        informational: false
    patch:
      default:
        # Keep patch advisory for now
        target: auto
        threshold: 0%
        informational: true

ignore:
  - "src/Starter/Database/Generated.hs"
