name: Integration

on:
  push:
  pull_request:

jobs:
  add-layer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.4"
          cabal-version: "3.12.1.0"
      - name: Install dependencies
        run: |
          cabal update
          cabal install hpack --installdir "$HOME/.local/bin" --overwrite-policy=always
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pip install PyYAML
      - name: Integration test for add_as_http_layer
        run: scripts/test_add_http_layer.sh
